sudo: required
services: 
   - docker
before_install:
  - curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
  - chmod +x $HOME/kubectl
  - mkdir -p $HOME/bin && cp $HOME/kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - kubectl version --short --client
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
  - chmod +x $HOME/aws-iam-authenticator
  - mkdir -p $HOME/bin && cp $HOME/aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
  - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - aws-iam-authenticator help