sudo: required
services: 
   - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1  
before_install:
  - pip install awscli --upgrade --user
  - mkdir -p ~/.kube && touch ~/.kube/config
  - mkdir -p ~/.aws && touch ~/.aws/config
  - echo '[default]' >> ~/.aws/config
  - echo "aws_access_key_id=$AWS_ACCESS_KEY" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_KEY" >> ~/.aws/config
  - echo "region=$AWS_REGION" >> ~/.aws/config
  - curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
  - chmod +x $TRAVIS_BUILD_DIR/kubectl
  - mkdir -p $HOME/bin && cp $TRAVIS_BUILD_DIR/kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
  - chmod +x $TRAVIS_BUILD_DIR/aws-iam-authenticator
  - mkdir -p $HOME/bin && cp $TRAVIS_BUILD_DIR/aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
  - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gbutchers/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gbutchers/docker-react npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master



